alias sag='sudo apt-get'
alias sagi='sudo apt-get install'
alias sagu='sudo apt-get update'
alias dovenv='source .env/bin/activate'
alias tmux='tmux -2'
alias py3='python3'
alias py='python'
alias xclip='xclip -selection c'
